AWSTemplateFormatVersion: "2010-09-09"
Description: Easy Static Site - S3 + CloudFront with external ACM certificate (us-east-1 only)

Rules:
  RequireUsEast1:
    Assertions:
      - Assert:
          Fn::Equals: [!Ref "AWS::Region", "us-east-1"]
        AssertDescription: "This template must be deployed in us-east-1 because CloudFront requires ACM certificates in us-east-1."

Parameters:
  DomainName:
    Type: String
    Description: Your domain (e.g., example.com)
  AcmCertificateArn:
    Type: String
    Description: ARN of your ACM certificate (must be in us-east-1, must cover domain + www)
    AllowedPattern: "arn:aws:acm:us-east-1:[0-9]+:certificate/.*"
    ConstraintDescription: Must be a valid ACM certificate ARN in us-east-1
  GitHubRepo:
    Type: String
    Description: "GitHub repo for OIDC (format: username/repo)"
  GitHubBranch:
    Type: String
    Default: main
    Description: Branch for OIDC trust

Resources:
  # S3 Bucket (private)
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${DomainName}-site-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  # OAC for CloudFront access to S3
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${DomainName}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  SiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: Distribution
    Properties:
      Bucket: !Ref SiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontServicePrincipalReadOnly
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action:
              - s3:GetObject
            Resource: !Sub "${SiteBucket.Arn}/*"
            Condition:
              StringLike:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/*"

  # CloudFront Function for www to apex redirect
  WwwRedirectFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: !Sub "${AWS::StackName}-www-redirect"
      AutoPublish: true
      FunctionCode: |
        function handler(event) {
          var host = event.request.headers.host.value;
          if (host.startsWith('www.')) {
            return {
              statusCode: 301,
              statusDescription: 'Moved Permanently',
              headers: { location: { value: 'https://' + host.substring(4) + event.request.uri } }
            };
          }
          return event.request;
        }
      FunctionConfig:
        Runtime: cloudfront-js-2.0
        Comment: Redirect www to apex domain

  # CloudFront Distribution
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
          - !Sub "www.${DomainName}"
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Managed-CachingOptimized
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt WwwRedirectFunction.FunctionARN
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        Enabled: true
        HttpVersion: http2and3
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt SiteBucket.RegionalDomainName
            OriginAccessControlId: !GetAtt OriginAccessControl.Id
            S3OriginConfig:
              OriginAccessIdentity: ""
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

  # OIDC Provider for GitHub Actions
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd

  # IAM Role for GitHub Actions OIDC
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-github-actions"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOIDCProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub "repo:${GitHubRepo}:ref:refs/heads/${GitHubBranch}"
      Policies:
        - PolicyName: DeployToS3AndCloudFront
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: S3Access
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt SiteBucket.Arn
                  - !Sub "${SiteBucket.Arn}/*"
              - Sid: CloudFrontInvalidation
                Effect: Allow
                Action:
                  - cloudfront:CreateInvalidation
                Resource: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution}"

Outputs:
  SiteBucketName:
    Value: !Ref SiteBucket
    Description: S3 bucket name - use as S3_BUCKET in GitHub
  CloudFrontDomainName:
    Value: !GetAtt Distribution.DomainName
    Description: Point your DNS CNAME/ALIAS to this value
  CloudFrontId:
    Value: !Ref Distribution
    Description: CloudFront distribution ID - use as CLOUDFRONT_ID in GitHub
  CloudFrontURL:
    Value: !Sub "https://${Distribution.DomainName}"
    Description: CloudFront URL (before custom domain is configured)
  GitHubRoleARN:
    Value: !GetAtt GitHubActionsRole.Arn
    Description: IAM role ARN - use as AWS_ROLE_ARN in GitHub
  SiteURL:
    Value: !Sub "https://${DomainName}"
    Description: Your site URL (after DNS is configured)
